### ISSUE TITLE
Failure to remove BringMe <key>. 

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/Caster#789]
**Describe the bug**
BringMe failure to femove a key from `bringme.toml`

**To Reproduce**
Steps to reproduce the behavior (be sure to include the exact command phrase you are using):
1. say `remove notepad from bring me`
2. Failure to remove `notepad` key from `bringme.toml` despite command being recognized. 

```toml
[program]
notepad = "C:\\Windows\\notepad.exe"
```
